name: Deploy Binaries

on: [push, pull_request]

jobs:
  deploy-windows:
    name: Deploy Windows
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          .venv/Scripts/activate
          python3 --version

      - name: Install setuptools, wheel
        run: >-
          python3 -m
          pip install
          setuptools wheel

      - name: Install requirements-nocore.txt
        run: >-
          python3 -m
          pip install
          -r requirements-nocore.txt

      - name: Install nuitka, imageio
        run: >-
          python3 -m
          pip install
          nuitka imageio

      - name: Set up go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install go 1.20 dependencies
        run: |
          go version
          python3 -m pip install "hysteria > 1.3.5"

      - name: Set up go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install go 1.21 dependencies
        run: |
          go version
          python3 -m pip install "tun2socks > 2.5.1"

      - name: Set up go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install go 1.22 dependencies
        run: |
          go version
          python3 -m pip install "Xray-core >= 1.8.8" "hysteria2 >= 2.0.4"

      - name: Run deploy script
        run: python3 Deploy.py

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: windows-distributions
          path: |
            *.zip
