name: Deploy PyPI

on: push

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 --version
      - name: Install libegl1
        run: |
          sudo apt update && sudo apt install -y libegl1
      - name: Install setuptools, wheel
        run: >-
          python3 -m
          pip install
          setuptools wheel
      - name: Install requirements-nocore.txt
        run: >-
          python3 -m
          pip install
          -r requirements-nocore.txt
      - name: Build a binary wheel and a source tarball
        run: python3 setup.py sdist bdist_wheel
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: deploy-pypi
      url: https://pypi.org/p/Furious-GUI
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
